# -----------------------------
# Reproducibility and resources
# -----------------------------
random_seed: 39809473   # Base seed reused across steps that require randomization, to ensure reproducibility.
max_threads: 16         # Default thread cap 

# -----------------------------
# treetime prunning values
# -----------------------------
treetime_parameters:
  clock_filter: 4.0   # Outlier detection threshold (number of interquartile ranges from regression)
# -----------------------------
# ML_parameters

# Outgroup root sample
outgroup_root_sample: "EPI_ISL_18133029" #muestra mas antigua para root

