# -----------------------------
# Reproducibility and resources
# -----------------------------
random_seed: 39809473   # Base seed reused across steps that require randomization, to ensure reproducibility.
max_threads: 18         # Default thread cap 
# -----------------------------
# BEAST exploratory runs
# -----------------------------
beast:
  enabled: true
  binary: null
  max_hours: 6
  threads: 18
  beagle:
    mode: auto
    vendor: amd
    resource: gpu
    platform: auto
    precision: auto
    scaling: default
    fallback_to_cpu: false
    info: true
  chain_length:
    strict_constant: 100000000
    strict_constant_lugar: 100000000
    ucln_constant: 120000000
    strict_exp: 100000000
    ucln_exp: 120000000
  log_every: 10000
  tree_every: 10000
  echo_every: 10000
  seeds:
    strict_constant: 3980
    strict_constant_lugar: 13980
    ucln_constant: 9473
    strict_exp: 10893
    ucln_exp: 3749

beast_panel:
  n_closest: 200
  max_distance: 0.08
  protect_anchors_count: 10

# Context subsampling (anti-duplication rule)
max_per_country_month: 2

# Maximum Likelihood (ML) tree replicates
iqtree_replicates: 10

# Northwestern/Pacific Flyway H5N1 outlier accessions to exclude
exclude_context_accessions:
  - "EPI_ISL_19145215"
  - "EPI_ISL_19151732"
  - "EPI_ISL_19158330"
  - "EPI_ISL_19303622"
  - "EPI_ISL_19158329"
  - "EPI_ISL_19151888"
  - "EPI_ISL_19157532"
  - "EPI_ISL_13117289"
  - "EPI_ISL_19151708"
  - "EPI_ISL_19151569"
  - "EPI_ISL_19151673"


