# =====================================================================
# PATHS CONFIGURATION
# Organization of inputs, intermediate data, and results.
# =====================================================================

# -----------------------------
# Inputs & Metadata
# -----------------------------
mira_base_dir: ""
flu_filtrado: "metadata/flu_filtrado.csv"
context_base: "metadata/context_base.csv" #metadata extracted from epi_set header from samples not assembled in house
context_fasta_raw: "data/context/gisaid_epiflu_sequence.fasta" # all fasta from epi_set not assembed in house
context_dir: "data/context" #also used for complete epi_set input as ecuadorian samples can be retrieved from it
context_genoflu_run: "data/context/genoflu_run" # workdir for genoflu_run

# -----------------------------
# Intermediate Directories (Data)
# -----------------------------
data_input: "data/input" #directory where MIRA input would go, also where ecuadorian samples retrieved from epi_set go
data_phylogeny: "data/phylogeny"
processed_alignments_codon_aware: "data/processed_alignments/codon_aware"
processed_alignments_qc_filtered: "data/processed_alignments/qc_filtered"

# -----------------------------
# Results Directories
# -----------------------------
results_phylogeny: "results/phylogeny"
results_qc_metrics: "results/qc_metrics"
