library(phytools)
tree1 <- rcoal(10)
tree2 <- rcoal(10)
tree1$tip.label <- as.character(1:10)
tree2$tip.label <- as.character(1:10)
obj <- cophylo(tree1, tree2)
plot(obj, ftype="off")
p <- get("last_plot.cophylo", envir = ape::.PlotPhyloEnv)
str(p)
